import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import StoreProvider from './store/StoreProvider';
import { ConfigProvider } from 'antd';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Stock Mgt Portal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {/** Wrap children with AntdRegistry to avoid page flicker */}
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: 'var(--primary-color)',
                colorPrimaryHover: 'var(--dark-color)',
                colorPrimaryBgHover: 'green',
                colorPrimaryBorder: 'var(--lighter-color)',
                colorPrimaryActive: 'var(--dark-color)',
                colorBorder: 'var(--lighter-color)',
                controlOutlineWidth: 0,
                colorPrimaryBorderHover: 'var(--lighter-color)',
              },
            }}
          >
            <StoreProvider>{children}</StoreProvider>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
