
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lakehouseenterprise-website
  labels:
    app: lakehouseenterprise-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lakehouseenterprise-website
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: lakehouseenterprise-website
    spec:
      containers:
      - name: lakehouseenterprise-website
        image: <IMAGE_NAME>:<TAG>
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        
      


---
apiVersion: v1
kind: Service
metadata:
  name: svc-lakehouseenterprise-website
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: lakehouseenterprise-website

